apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smart-scalers.gmarciani.com
  finalizers:
  - finalizer.smart-scalers.gmarciani.com
spec:
  group: gmarciani.com
  version: v1
  scope: Namespaced
  names:
    plural: smart-scalers
    singular: smart-scaler
    kind: SmartScaler
    shortNames:
      - ss
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - deployment
            - algorithm
          properties:
            deployment:
              type: string
            algorithm:
              type: string
              enum:
                - qlearning
                - sarsa
            parameters:
              type: object
            replicationMin:
              type: integer
            replicationMax:
              type: integer
